/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellWithUsRouteImport } from './routes/sell-with-us'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PartyOrdersRouteImport } from './routes/party-orders'
import { Route as OverseasRouteImport } from './routes/overseas'
import { Route as OrderRouteImport } from './routes/order'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BacklinksRouteImport } from './routes/backlinks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellWithUsRoute = SellWithUsRouteImport.update({
  id: '/sell-with-us',
  path: '/sell-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyOrdersRoute = PartyOrdersRouteImport.update({
  id: '/party-orders',
  path: '/party-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OverseasRoute = OverseasRouteImport.update({
  id: '/overseas',
  path: '/overseas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklinksRoute = BacklinksRouteImport.update({
  id: '/backlinks',
  path: '/backlinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/backlinks': typeof BacklinksRoute
  '/contact': typeof ContactRoute
  '/dealers': typeof DealersRoute
  '/faq': typeof FaqRoute
  '/order': typeof OrderRoute
  '/overseas': typeof OverseasRoute
  '/party-orders': typeof PartyOrdersRoute
  '/products': typeof ProductsRoute
  '/reviews': typeof ReviewsRoute
  '/sell-with-us': typeof SellWithUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/backlinks': typeof BacklinksRoute
  '/contact': typeof ContactRoute
  '/dealers': typeof DealersRoute
  '/faq': typeof FaqRoute
  '/order': typeof OrderRoute
  '/overseas': typeof OverseasRoute
  '/party-orders': typeof PartyOrdersRoute
  '/products': typeof ProductsRoute
  '/reviews': typeof ReviewsRoute
  '/sell-with-us': typeof SellWithUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/backlinks': typeof BacklinksRoute
  '/contact': typeof ContactRoute
  '/dealers': typeof DealersRoute
  '/faq': typeof FaqRoute
  '/order': typeof OrderRoute
  '/overseas': typeof OverseasRoute
  '/party-orders': typeof PartyOrdersRoute
  '/products': typeof ProductsRoute
  '/reviews': typeof ReviewsRoute
  '/sell-with-us': typeof SellWithUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/backlinks'
    | '/contact'
    | '/dealers'
    | '/faq'
    | '/order'
    | '/overseas'
    | '/party-orders'
    | '/products'
    | '/reviews'
    | '/sell-with-us'
    | '/sitemap.xml'
    | '/suggestions'
    | '/terms'
    | '/training'
    | '/dashboard'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/backlinks'
    | '/contact'
    | '/dealers'
    | '/faq'
    | '/order'
    | '/overseas'
    | '/party-orders'
    | '/products'
    | '/reviews'
    | '/sell-with-us'
    | '/sitemap.xml'
    | '/suggestions'
    | '/terms'
    | '/training'
    | '/dashboard'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/backlinks'
    | '/contact'
    | '/dealers'
    | '/faq'
    | '/order'
    | '/overseas'
    | '/party-orders'
    | '/products'
    | '/reviews'
    | '/sell-with-us'
    | '/sitemap.xml'
    | '/suggestions'
    | '/terms'
    | '/training'
    | '/_authenticated/dashboard'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BacklinksRoute: typeof BacklinksRoute
  ContactRoute: typeof ContactRoute
  DealersRoute: typeof DealersRoute
  FaqRoute: typeof FaqRoute
  OrderRoute: typeof OrderRoute
  OverseasRoute: typeof OverseasRoute
  PartyOrdersRoute: typeof PartyOrdersRoute
  ProductsRoute: typeof ProductsRoute
  ReviewsRoute: typeof ReviewsRoute
  SellWithUsRoute: typeof SellWithUsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuggestionsRoute: typeof SuggestionsRoute
  TermsRoute: typeof TermsRoute
  TrainingRoute: typeof TrainingRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-with-us': {
      id: '/sell-with-us'
      path: '/sell-with-us'
      fullPath: '/sell-with-us'
      preLoaderRoute: typeof SellWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-orders': {
      id: '/party-orders'
      path: '/party-orders'
      fullPath: '/party-orders'
      preLoaderRoute: typeof PartyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overseas': {
      id: '/overseas'
      path: '/overseas'
      fullPath: '/overseas'
      preLoaderRoute: typeof OverseasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlinks': {
      id: '/backlinks'
      path: '/backlinks'
      fullPath: '/backlinks'
      preLoaderRoute: typeof BacklinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BacklinksRoute: BacklinksRoute,
  ContactRoute: ContactRoute,
  DealersRoute: DealersRoute,
  FaqRoute: FaqRoute,
  OrderRoute: OrderRoute,
  OverseasRoute: OverseasRoute,
  PartyOrdersRoute: PartyOrdersRoute,
  ProductsRoute: ProductsRoute,
  ReviewsRoute: ReviewsRoute,
  SellWithUsRoute: SellWithUsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuggestionsRoute: SuggestionsRoute,
  TermsRoute: TermsRoute,
  TrainingRoute: TrainingRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
